<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database "globalnew"
//

// globalnew.ingatlan_trans
$zonak = array(
  array('telepules'=>'Pécs','db'=>'288'),
  array('telepules'=>'Kozármisleny','db'=>'16'),
  array('telepules'=>'Budapest','db'=>'9'),
  array('telepules'=>'Pogány','db'=>'7'),
  array('telepules'=>'Nagykozár','db'=>'5'),
  array('telepules'=>'Budapest XII.','db'=>'5'),
  array('telepules'=>'Budapest II. kerület','db'=>'5'),
  array('telepules'=>'Pellérd','db'=>'5'),
  array('telepules'=>'Egerág','db'=>'5'),
  array('telepules'=>'Keszü','db'=>'4'),
  array('telepules'=>'Budapest - II. kerület - Budaliget','db'=>'4'),
  array('telepules'=>'Pécs-Hird','db'=>'4'),
  array('telepules'=>'Budapest, XI ker.','db'=>'3'),
  array('telepules'=>'Orfű','db'=>'3'),
  array('telepules'=>'Harkány','db'=>'3'),
  array('telepules'=>'Pécs-nyugat közeli ','db'=>'2'),
  array('telepules'=>'Mohács','db'=>'2'),
  array('telepules'=>'Bogád','db'=>'2'),
  array('telepules'=>'Budapest, V.','db'=>'2'),
  array('telepules'=>'Hásságy','db'=>'2'),
  array('telepules'=>'Sikonda','db'=>'2'),
  array('telepules'=>'Pécsudvard','db'=>'2'),
  array('telepules'=>'Babarc','db'=>'2'),
  array('telepules'=>'Áta ','db'=>'2'),
  array('telepules'=>'Budapest III. kerület Ürömhegy','db'=>'2'),
  array('telepules'=>'Harkány, ','db'=>'2'),
  array('telepules'=>'Szentlőrinc','db'=>'2'),
  array('telepules'=>'Pécs mellett','db'=>'2'),
  array('telepules'=>'Sásd','db'=>'1'),
  array('telepules'=>'Pécs-Kővágószőllős között','db'=>'1'),
  array('telepules'=>'Pécs-Cserkút','db'=>'1'),
  array('telepules'=>'Pécs-Somogy','db'=>'1'),
  array('telepules'=>'Budapest - Budaliget - II/a kerület','db'=>'1'),
  array('telepules'=>'Rédics','db'=>'1'),
  array('telepules'=>'Szászvár','db'=>'1'),
  array('telepules'=>'Gemenc','db'=>'1'),
  array('telepules'=>'Budapest - II. kerület - Máriaremete','db'=>'1'),
  array('telepules'=>'Üröm','db'=>'1'),
  array('telepules'=>'Budapest -II. kerület - Hidegkút','db'=>'1'),
  array('telepules'=>'Budapest - II. kerület - Hűvösvölgy','db'=>'1'),
  array('telepules'=>'Budapest VII. kerület','db'=>'1'),
  array('telepules'=>'Pécs-Nagyárpád','db'=>'1'),
  array('telepules'=>'Balatonfenyves','db'=>'1'),
  array('telepules'=>'Pécs mellett, Cserkúton','db'=>'1'),
  array('telepules'=>'Görcsöny','db'=>'1'),
  array('telepules'=>'Szemely','db'=>'1'),
  array('telepules'=>'Berkesd','db'=>'1'),
  array('telepules'=>'Balatonszárszó','db'=>'1'),
  array('telepules'=>'Isaszeg','db'=>'1'),
  array('telepules'=>'Brodarica (CRO)','db'=>'1'),
  array('telepules'=>'Budapest II. ker.','db'=>'1'),
  array('telepules'=>'Pécsbánya','db'=>'1'),
  array('telepules'=>'Budapest, VII. kerület','db'=>'1'),
  array('telepules'=>'Szalánta','db'=>'1'),
  array('telepules'=>'Aranyosgadány','db'=>'1'),
  array('telepules'=>'Csatahely','db'=>'1'),
  array('telepules'=>'Pogány (reptér közelében)','db'=>'1'),
  array('telepules'=>'Keszü Újtelep','db'=>'1'),
  array('telepules'=>'Hosszúhetény','db'=>'1'),
  array('telepules'=>'Cserkút','db'=>'1'),
  array('telepules'=>'Budapest, XIII.','db'=>'1'),
  array('telepules'=>'Diosviszló','db'=>'1'),
  array('telepules'=>'Budapest, II. kerület','db'=>'1'),
  array('telepules'=>'Budapest III. Csillaghegy','db'=>'1'),
  array('telepules'=>'Balaton','db'=>'1'),
  array('telepules'=>'Boldogasszonyfa','db'=>'1'),
  array('telepules'=>'Siklós','db'=>'1'),
  array('telepules'=>'Magyarbóly','db'=>'1'),
  array('telepules'=>'Budapest - Svábhegy - XII. kerület','db'=>'1'),
  array('telepules'=>'Tenkes hegy','db'=>'1'),
  array('telepules'=>'Pécs Vasas','db'=>'1'),
  array('telepules'=>'Kaposszekcső','db'=>'1'),
  array('telepules'=>'Budapest - II/a kerület - Budaliget','db'=>'1'),
  array('telepules'=>'PÉcs (Hird)','db'=>'1'),
  array('telepules'=>'Véménd','db'=>'1'),
  array('telepules'=>'Bátaszék, Tolna megye','db'=>'1')
);
